/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#304d3e",
        "surface-container-low": "#0f1d24",
        "on-tertiary-fixed-variant": "#623d3e",
        "on-tertiary-container": "#c19192",
        "on-tertiary-fixed": "#301314",
        "primary-fixed": "#c9ead6",
        "tertiary-container": "#4d2b2c",
        "inverse-on-surface": "#243239",
        "surface-bright": "#2d3b42",
        tertiary: "#eebaba",
        "inverse-surface": "#d5e5ee",
        "on-primary-fixed": "#032014",
        "on-primary": "#193628",
        background: "#050505",
        error: "#ffb4ab",
        "primary-container": "#1d3a2c",
        "secondary-fixed-dim": "#b4c6f4",
        "on-surface-variant": "#c2c8c2",
        "on-error-container": "#ffdad6",
        surface: "#050505",
        "on-background": "#d5e5ee",
        "surface-container-lowest": "#031016",
        outline: "#1A1A1A",
        "on-primary-container": "#84a492",
        "tertiary-fixed": "#ffdad9",
        primary: "#adceba",
        "surface-container": "#132128",
        "on-tertiary": "#482728",
        "on-secondary-fixed-variant": "#34466d",
        "secondary-fixed": "#d9e2ff",
        "tertiary-fixed-dim": "#eebaba",
        "secondary-container": "#34466d",
        "surface-dim": "#07151b",
        "inverse-primary": "#476555",
        "error-container": "#93000a",
        "surface-container-high": "#1e2c33",
        "outline-variant": "#424844",
        "surface-variant": "#29373e",
        "on-secondary-fixed": "#041a3f",
        "on-secondary-container": "#a3b5e2",
        "on-error": "#690005",
        "primary-fixed-dim": "#adceba",
        secondary: "#b4c6f4",
        "surface-tint": "#adceba",
        "surface-container-highest": "#29373e",
        "on-surface": "#d5e5ee",
        "on-secondary": "#1d2f55",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "80px",
        "container-max": "1440px",
        gutter: "24px",
        "margin-mobile": "20px",
        unit: "4px",
      },
      fontFamily: {
        "label-sm": ["JetBrains Mono", "monospace"],
        "mono-code": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Geist", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Geist", "system-ui", "sans-serif"],
        "body-md": ["Geist", "system-ui", "sans-serif"],
        "display-lg": ["Geist", "system-ui", "sans-serif"],
      },
      fontSize: {
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "mono-code": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.01em",
            fontWeight: "500",
          },
        ],
        "headline-lg-mobile": [
          "24px",
          {
            lineHeight: "32px",
            letterSpacing: "-0.01em",
            fontWeight: "500",
          },
        ],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "display-lg": [
          "64px",
          {
            lineHeight: "72px",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
      },
    },
  },
  plugins: [],
};
