/** @type {import('tailwindcss').Config} */
/** Tokens: DESIGN (1).md — Vector Engineering Lab (premium light) */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#faf9f6",
        "on-background": "#1a1c1b",
        surface: "#faf9f6",
        "surface-dim": "#dadad7",
        "surface-bright": "#faf9f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f4f1",
        "surface-container": "#eeeeeb",
        "surface-container-high": "#e9e8e5",
        "surface-container-highest": "#e3e2e0",
        "surface-variant": "#e3e2e0",
        "on-surface": "#1a1c1b",
        "on-surface-variant": "#424844",
        "inverse-surface": "#2f312f",
        "inverse-on-surface": "#f1f1ee",
        outline: "#727973",
        "outline-variant": "#c2c8c2",
        "surface-tint": "#476555",
        /** Forest green — CTAs e iconos técnicos (design doc) */
        primary: "#1d3a2c",
        "on-primary": "#ffffff",
        /** Verde muy oscuro — acentos de marca YAML */
        "primary-deep": "#062418",
        "primary-container": "#1d3a2c",
        "on-primary-container": "#84a492",
        "inverse-primary": "#adceba",
        "primary-fixed": "#c9ead6",
        "primary-fixed-dim": "#adceba",
        "on-primary-fixed": "#032014",
        "on-primary-fixed-variant": "#304d3e",
        secondary: "#4c5e86",
        "on-secondary": "#ffffff",
        "secondary-container": "#bccefd",
        "on-secondary-container": "#46577f",
        "secondary-fixed": "#d9e2ff",
        "secondary-fixed-dim": "#b4c6f4",
        "on-secondary-fixed": "#041a3f",
        "on-secondary-fixed-variant": "#34466d",
        tertiary: "#341618",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#4d2b2c",
        "on-tertiary-container": "#c19192",
        "tertiary-fixed": "#ffdad9",
        "tertiary-fixed-dim": "#eebaba",
        "on-tertiary-fixed": "#301314",
        "on-tertiary-fixed-variant": "#623d3e",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        /** Navy — peso en navegación y titulares (design doc) */
        navy: "#0a1f44",
        /** Utilidades de capa (prosa DESIGN) */
        "surface-elevated": "#f8fafc",
        "border-subtle": "#e2e8f0",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "48px",
        "container-max": "1280px",
        gutter: "24px",
        "margin-mobile": "16px",
        unit: "4px",
      },
      fontFamily: {
        "label-sm": ["Geist", "system-ui", "sans-serif"],
        "label-md": ["Geist", "system-ui", "sans-serif"],
        "mono-code": ["JetBrains Mono", "ui-monospace", "monospace"],
        "headline-lg": ["Geist", "system-ui", "sans-serif"],
        "headline-md": ["Geist", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Geist", "system-ui", "sans-serif"],
        "body-md": ["Geist", "system-ui", "sans-serif"],
        "body-lg": ["Geist", "system-ui", "sans-serif"],
        "body-sm": ["Geist", "system-ui", "sans-serif"],
        "display-lg": ["Geist", "system-ui", "sans-serif"],
      },
      fontSize: {
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "label-md": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "mono-code": ["13px", { lineHeight: "1", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": [
          "24px",
          { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "500" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "500" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "500" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "600" },
        ],
      },
      boxShadow: {
        ambient: "0 4px 20px rgba(10, 31, 68, 0.04)",
      },
    },
  },
  plugins: [],
};
